# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import log, cos, sin, tan

class Calculator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 342)
        MainWindow.setStyleSheet("background-color:rgbrgb(0, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/AnimeX/AnimeX_1054187.jpeg"))
        self.label.setObjectName("label")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(20, 169, 77, 23))
        self.Button1.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button1.setObjectName("Button1")
        self.ButtonMul = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonMul.setGeometry(QtCore.QRect(270, 169, 77, 23))
        self.ButtonMul.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonMul.setObjectName("ButtonMul")
        self.Lable1 = QtWidgets.QLabel(self.centralwidget)
        self.Lable1.setGeometry(QtCore.QRect(18, 40, 324, 51))
        self.Lable1.setStyleSheet("color:rgb(255, 255, 255)")
        self.Lable1.setFrameShape(QtWidgets.QFrame.Panel)
        self.Lable1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lable1.setText("")
        self.Lable1.setObjectName("Lable1")
        self.ButtonDiv = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDiv.setGeometry(QtCore.QRect(270, 198, 77, 23))
        self.ButtonDiv.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonDiv.setObjectName("ButtonDiv")
        self.ButtonRBracket = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonRBracket.setGeometry(QtCore.QRect(185, 256, 77, 23))
        self.ButtonRBracket.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonRBracket.setObjectName("ButtonRBracket")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(103, 169, 76, 23))
        self.Button2.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button2.setObjectName("Button2")
        self.ButtonClear = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonClear.setEnabled(True)
        self.ButtonClear.setGeometry(QtCore.QRect(20, 256, 77, 23))
        self.ButtonClear.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonClear.setObjectName("ButtonClear")
        self.ButtonLBracket = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonLBracket.setGeometry(QtCore.QRect(103, 256, 77, 23))
        self.ButtonLBracket.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonLBracket.setObjectName("ButtonLBracket")
        self.ButtonSin = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSin.setGeometry(QtCore.QRect(103, 227, 77, 23))
        self.ButtonSin.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonSin.setObjectName("ButtonSin")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button5.setGeometry(QtCore.QRect(103, 140, 76, 23))
        self.Button5.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button5.setObjectName("Button5")
        self.Button6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button6.setGeometry(QtCore.QRect(185, 140, 77, 23))
        self.Button6.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button6.setObjectName("Button6")
        self.ButtonSub = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSub.setGeometry(QtCore.QRect(270, 140, 77, 23))
        self.ButtonSub.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonSub.setObjectName("ButtonSub")
        self.ButtonLog = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonLog.setGeometry(QtCore.QRect(103, 198, 77, 23))
        self.ButtonLog.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonLog.setObjectName("ButtonLog")
        self.ButtonTan = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonTan.setGeometry(QtCore.QRect(20, 227, 77, 23))
        self.ButtonTan.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonTan.setObjectName("ButtonTan")
        self.Button9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button9.setGeometry(QtCore.QRect(185, 111, 77, 23))
        self.Button9.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button9.setObjectName("Button9")
        self.Button0 = QtWidgets.QPushButton(self.centralwidget)
        self.Button0.setGeometry(QtCore.QRect(20, 198, 77, 23))
        self.Button0.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button0.setObjectName("Button0")
        self.ButtonPeriod = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonPeriod.setGeometry(QtCore.QRect(185, 198, 77, 23))
        self.ButtonPeriod.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonPeriod.setObjectName("ButtonPeriod")
        self.ButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonAdd.setGeometry(QtCore.QRect(270, 111, 77, 23))
        self.ButtonAdd.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonAdd.setObjectName("ButtonAdd")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(185, 169, 77, 23))
        self.Button3.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button3.setObjectName("Button3")
        self.ButtonCos = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonCos.setGeometry(QtCore.QRect(185, 227, 77, 23))
        self.ButtonCos.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.ButtonCos.setObjectName("ButtonCos")
        self.Button7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button7.setGeometry(QtCore.QRect(20, 111, 77, 23))
        self.Button7.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button7.setObjectName("Button7")
        self.Button8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button8.setGeometry(QtCore.QRect(103, 111, 76, 23))
        self.Button8.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button8.setObjectName("Button8")
        self.ButtonEqual = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonEqual.setGeometry(QtCore.QRect(270, 227, 77, 51))
        self.ButtonEqual.setAutoFillBackground(False)
        self.ButtonEqual.setStyleSheet("font: 16pt \"MS Serif\";\n"
"background-color:rgb(197, 193, 255)")
        self.ButtonEqual.setObjectName("ButtonEqual")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button4.setGeometry(QtCore.QRect(20, 140, 77, 23))
        self.Button4.setStyleSheet("background-color:rgb(197, 193, 255)")
        self.Button4.setObjectName("Button4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        # List for Reference to Label Display
        self.screenLabel_display = []

        # Behavior of GUI
        self.Button1.clicked.connect(self.click_button_1)
        self.Button2.clicked.connect(self.click_button_2)
        self.Button3.clicked.connect(self.click_button_3)
        self.Button4.clicked.connect(self.click_button_4)
        self.Button5.clicked.connect(self.click_button_5)
        self.Button6.clicked.connect(self.click_button_6)
        self.Button7.clicked.connect(self.click_button_7)
        self.Button8.clicked.connect(self.click_button_8)
        self.Button9.clicked.connect(self.click_button_9)
        self.Button0.clicked.connect(self.click_button_0)
        self.ButtonEqual.clicked.connect(self.click_button_equal)
        self.ButtonAdd.clicked.connect(self.click_button_add)
        self.ButtonSub.clicked.connect(self.click_button_sub)
        self.ButtonDiv.clicked.connect(self.click_button_div)
        self.ButtonMul.clicked.connect(self.click_button_mul)
        self.ButtonPeriod.clicked.connect(self.click_button_period)
        self.ButtonLog.clicked.connect(self.click_button_log)
        self.ButtonTan.clicked.connect(self.click_button_tan)
        self.ButtonSin.clicked.connect(self.click_button_sin)
        self.ButtonCos.clicked.connect(self.click_button_cos)
        self.ButtonClear.clicked.connect(self.click_button_clear)
        self.ButtonLBracket.clicked.connect(self.click_button_lbracket)
        self.ButtonRBracket.clicked.connect(self.click_button_rbracket)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button1.setShortcut(_translate("MainWindow", "1"))
        self.ButtonMul.setText(_translate("MainWindow", "*"))
        self.ButtonMul.setShortcut(_translate("MainWindow", "*"))
        self.ButtonDiv.setText(_translate("MainWindow", "/"))
        self.ButtonDiv.setShortcut(_translate("MainWindow", "/"))
        self.ButtonRBracket.setText(_translate("MainWindow", ")"))
        self.ButtonRBracket.setShortcut(_translate("MainWindow", ")"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button2.setShortcut(_translate("MainWindow", "2"))
        self.ButtonClear.setText(_translate("MainWindow", "clear"))
        self.ButtonClear.setShortcut(_translate("MainWindow", "Backspace"))
        self.ButtonLBracket.setText(_translate("MainWindow", "("))
        self.ButtonLBracket.setShortcut(_translate("MainWindow", "("))
        self.ButtonSin.setText(_translate("MainWindow", "sin"))
        self.ButtonSin.setShortcut(_translate("MainWindow", "S"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Button5.setShortcut(_translate("MainWindow", "5"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button6.setShortcut(_translate("MainWindow", "6"))
        self.ButtonSub.setText(_translate("MainWindow", "-"))
        self.ButtonSub.setShortcut(_translate("MainWindow", "-"))
        self.ButtonLog.setText(_translate("MainWindow", "log"))
        self.ButtonLog.setShortcut(_translate("MainWindow", "L"))
        self.ButtonTan.setText(_translate("MainWindow", "tan"))
        self.ButtonTan.setShortcut(_translate("MainWindow", "T"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button9.setShortcut(_translate("MainWindow", "9"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.Button0.setShortcut(_translate("MainWindow", "0"))
        self.ButtonPeriod.setText(_translate("MainWindow", "."))
        self.ButtonPeriod.setShortcut(_translate("MainWindow", "."))
        self.ButtonAdd.setText(_translate("MainWindow", "+"))
        self.ButtonAdd.setShortcut(_translate("MainWindow", "+"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button3.setShortcut(_translate("MainWindow", "3"))
        self.ButtonCos.setText(_translate("MainWindow", "cos"))
        self.ButtonCos.setShortcut(_translate("MainWindow", "C"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.Button7.setShortcut(_translate("MainWindow", "7"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.Button8.setShortcut(_translate("MainWindow", "8"))
        self.ButtonEqual.setText(_translate("MainWindow", "="))
        self.ButtonEqual.setShortcut(_translate("MainWindow", "Return"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button4.setShortcut(_translate("MainWindow", "4"))


    def click_button_1(self):
        self.screenLabel_display.append('1')
        self.Lable1.setText(''.join(self.screenLabel_display))
      

    def click_button_2(self):
        self.screenLabel_display.append('2')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_3(self):
        self.screenLabel_display.append('3')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_4(self):
        self.screenLabel_display.append('4')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_5(self):
        self.screenLabel_display.append('5')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_6(self):
        self.screenLabel_display.append('6')
        self.Lable1.setText(''.join(self.screenLabel_display))
      

    def click_button_7(self):
        self.screenLabel_display.append('7')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_8(self):
        self.screenLabel_display.append('8')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_9(self):
        self.screenLabel_display.append('9')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_0(self):
        self.screenLabel_display.append('0')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_period(self):
        self.screenLabel_display.append('.')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_add(self):
        self.screenLabel_display.append('+')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_sub(self):
        self.screenLabel_display.append('-')
        self.Lable1.setText(''.join(self.screenLabel_display))

    def click_button_mul(self):
        self.screenLabel_display.append('*')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_div(self):
        self.screenLabel_display.append('/')
        self.Lable1.setText(''.join(self.screenLabel_display))
      
    def click_button_log(self):
        self.screenLabel_display.append('log(')
        self.Lable1.setText(''.join(self.screenLabel_display))

    def click_button_tan(self):
        self.screenLabel_display.append('tan(')
        self.Lable1.setText(''.join(self.screenLabel_display))

    def click_button_sin(self):
        self.screenLabel_display.append('sin(')
        self.Lable1.setText(''.join(self.screenLabel_display))
    
    def click_button_cos(self):
        self.screenLabel_display.append('cos(')
        self.Lable1.setText(''.join(self.screenLabel_display))
    
    def click_button_equal(self):
        try:
            data = ''.join(self.screenLabel_display)        
            ans = round(eval(data), 5)
            self.Lable1.setText(str(ans))
            self.screenLabel_display = [str(ans)]
        except:
            self.screenLabel_display = []
            self.Lable1.setText('Math Error. Try Again.')

    
    def click_button_clear(self):
        self.screenLabel_display.pop()
        self.Lable1.setText(''.join(self.screenLabel_display))

        
    def click_button_rbracket(self):
        self.screenLabel_display.append(')')
        self.Lable1.setText(''.join(self.screenLabel_display))
    
        
    def click_button_lbracket(self):
        self.screenLabel_display.append('(')
        self.Lable1.setText(''.join(self.screenLabel_display))
           
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    calculator = Calculator()
    calculator.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
